name: Deploy with SSh
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploying using SSH
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{secrets.SERVER_IP}}
          username: ubuntu
          key: ${{secrets.STAGE_SSH_KEY}}
          port: 22
          script: |
            cd new_basic-evops
            git add -A
            git commit -m "add done"
            git pull origin main
            npm install
            npm run build
            pm2 restart fe
            pm2 restart http-server
            pm2 restart ws-server