name: Deploying to the ec2
on:
  push:
    branches:
      - "main"

jobs:
  deploy_allInOne:
    name: delpoying all the changes
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server and restart
        run: |
          echo "${{secrets.STAGE_SSH_KEY}}" > ~/ssh_key
          chmod 700 ~/ssh_key
          mkdir -p ~/.ssh
          echo "${{secrets.KNOWN_HOSTS}}" > ~/.ssh/known_hosts
          ssh -i ~/ssh_key ubuntu@16.171.162.99 -t "export NVM_DIR="$HOME/.nvm" && source "$NVM_DIR/nvm.sh" && cd new_basic-evops && git pull origin main && npm install && npm run build && pm2 restart fe && pm2 restart http-server && pm2 restart ws-server"

      